package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Chucvu generated by hbm2java
 */
public class Chucvu  implements java.io.Serializable {


     private Integer idchucvu;
     private String ten;
     private Set soyeulylichs = new HashSet(0);

    public Chucvu() {
    }

    public Chucvu(String ten, Set soyeulylichs) {
       this.ten = ten;
       this.soyeulylichs = soyeulylichs;
    }
   
    public Integer getIdchucvu() {
        return this.idchucvu;
    }
    
    public void setIdchucvu(Integer idchucvu) {
        this.idchucvu = idchucvu;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getSoyeulylichs() {
        return this.soyeulylichs;
    }
    
    public void setSoyeulylichs(Set soyeulylichs) {
        this.soyeulylichs = soyeulylichs;
    }




}


