package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA



/**
 * Dienbienhocham generated by hbm2java
 */
public class Dienbienhocham  implements java.io.Serializable {


     private Integer iddienbienhocham;
     private Soyeulylich soyeulylich;
     private Hocham hocham;
     private String chuyennganh;
     private String namphong;

    public Dienbienhocham() {
    }

	
    public Dienbienhocham(Soyeulylich soyeulylich, Hocham hocham) {
        this.soyeulylich = soyeulylich;
        this.hocham = hocham;
    }
    public Dienbienhocham(Soyeulylich soyeulylich, Hocham hocham, String chuyennganh, String namphong) {
       this.soyeulylich = soyeulylich;
       this.hocham = hocham;
       this.chuyennganh = chuyennganh;
       this.namphong = namphong;
    }
   
    public Integer getIddienbienhocham() {
        return this.iddienbienhocham;
    }
    
    public void setIddienbienhocham(Integer iddienbienhocham) {
        this.iddienbienhocham = iddienbienhocham;
    }
    public Soyeulylich getSoyeulylich() {
        return this.soyeulylich;
    }
    
    public void setSoyeulylich(Soyeulylich soyeulylich) {
        this.soyeulylich = soyeulylich;
    }
    public Hocham getHocham() {
        return this.hocham;
    }
    
    public void setHocham(Hocham hocham) {
        this.hocham = hocham;
    }
    public String getChuyennganh() {
        return this.chuyennganh;
    }
    
    public void setChuyennganh(String chuyennganh) {
        this.chuyennganh = chuyennganh;
    }
    public String getNamphong() {
        return this.namphong;
    }
    
    public void setNamphong(String namphong) {
        this.namphong = namphong;
    }




}


