package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA



/**
 * Dienbienhocvi generated by hbm2java
 */
public class Dienbienhocvi  implements java.io.Serializable {


     private Integer iddienbienhocvi;
     private Hocvi hocvi;
     private Soyeulylich soyeulylich;
     private String namphong;

    public Dienbienhocvi() {
    }

	
    public Dienbienhocvi(Hocvi hocvi, Soyeulylich soyeulylich) {
        this.hocvi = hocvi;
        this.soyeulylich = soyeulylich;
    }
    public Dienbienhocvi(Hocvi hocvi, Soyeulylich soyeulylich, String namphong) {
       this.hocvi = hocvi;
       this.soyeulylich = soyeulylich;
       this.namphong = namphong;
    }
   
    public Integer getIddienbienhocvi() {
        return this.iddienbienhocvi;
    }
    
    public void setIddienbienhocvi(Integer iddienbienhocvi) {
        this.iddienbienhocvi = iddienbienhocvi;
    }
    public Hocvi getHocvi() {
        return this.hocvi;
    }
    
    public void setHocvi(Hocvi hocvi) {
        this.hocvi = hocvi;
    }
    public Soyeulylich getSoyeulylich() {
        return this.soyeulylich;
    }
    
    public void setSoyeulylich(Soyeulylich soyeulylich) {
        this.soyeulylich = soyeulylich;
    }
    public String getNamphong() {
        return this.namphong;
    }
    
    public void setNamphong(String namphong) {
        this.namphong = namphong;
    }




}


