package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Donviquanly generated by hbm2java
 */
public class Donviquanly  implements java.io.Serializable {


     private Integer iddonviquanly;
     private Khoidonviquanly khoidonviquanly;
     private String ten;
     private String nhiemvu;
     private String chucnang;
     private String diachitruso;
     private String dienthoai;
     private String email;
     private String fax;
     private String duongdananh;
     private Set phongbans = new HashSet(0);
     private Set soyeulylichs = new HashSet(0);

    public Donviquanly() {
    }

    public Donviquanly(Khoidonviquanly khoidonviquanly, String ten, String nhiemvu, String chucnang, String diachitruso, String dienthoai, String email, String fax, String duongdananh, Set phongbans, Set soyeulylichs) {
       this.khoidonviquanly = khoidonviquanly;
       this.ten = ten;
       this.nhiemvu = nhiemvu;
       this.chucnang = chucnang;
       this.diachitruso = diachitruso;
       this.dienthoai = dienthoai;
       this.email = email;
       this.fax = fax;
       this.duongdananh = duongdananh;
       this.phongbans = phongbans;
       this.soyeulylichs = soyeulylichs;
    }
   
    public Integer getIddonviquanly() {
        return this.iddonviquanly;
    }
    
    public void setIddonviquanly(Integer iddonviquanly) {
        this.iddonviquanly = iddonviquanly;
    }
    public Khoidonviquanly getKhoidonviquanly() {
        return this.khoidonviquanly;
    }
    
    public void setKhoidonviquanly(Khoidonviquanly khoidonviquanly) {
        this.khoidonviquanly = khoidonviquanly;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getNhiemvu() {
        return this.nhiemvu;
    }
    
    public void setNhiemvu(String nhiemvu) {
        this.nhiemvu = nhiemvu;
    }
    public String getChucnang() {
        return this.chucnang;
    }
    
    public void setChucnang(String chucnang) {
        this.chucnang = chucnang;
    }
    public String getDiachitruso() {
        return this.diachitruso;
    }
    
    public void setDiachitruso(String diachitruso) {
        this.diachitruso = diachitruso;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getDuongdananh() {
        return this.duongdananh;
    }
    
    public void setDuongdananh(String duongdananh) {
        this.duongdananh = duongdananh;
    }
    public Set getPhongbans() {
        return this.phongbans;
    }
    
    public void setPhongbans(Set phongbans) {
        this.phongbans = phongbans;
    }
    public Set getSoyeulylichs() {
        return this.soyeulylichs;
    }
    
    public void setSoyeulylichs(Set soyeulylichs) {
        this.soyeulylichs = soyeulylichs;
    }




}


