package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Giaoducphothong generated by hbm2java
 */
public class Giaoducphothong  implements java.io.Serializable {


     private Integer idgiaoducphothong;
     private String ten;
     private Set soyeulylichs = new HashSet(0);

    public Giaoducphothong() {
    }

    public Giaoducphothong(String ten, Set soyeulylichs) {
       this.ten = ten;
       this.soyeulylichs = soyeulylichs;
    }
   
    public Integer getIdgiaoducphothong() {
        return this.idgiaoducphothong;
    }
    
    public void setIdgiaoducphothong(Integer idgiaoducphothong) {
        this.idgiaoducphothong = idgiaoducphothong;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getSoyeulylichs() {
        return this.soyeulylichs;
    }
    
    public void setSoyeulylichs(Set soyeulylichs) {
        this.soyeulylichs = soyeulylichs;
    }




}


