package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Khoidonviquanly generated by hbm2java
 */
public class Khoidonviquanly  implements java.io.Serializable {


     private Integer idkhoidonviquanly;
     private String ten;
     private Set<Donviquanly> donviquanlies = new HashSet<Donviquanly>(0);

    public Khoidonviquanly() {
    }

    public Khoidonviquanly(String ten, Set<Donviquanly> donviquanlies) {
       this.ten = ten;
       this.donviquanlies = donviquanlies;
    }
   
    public Integer getIdkhoidonviquanly() {
        return this.idkhoidonviquanly;
    }
    
    public void setIdkhoidonviquanly(Integer idkhoidonviquanly) {
        this.idkhoidonviquanly = idkhoidonviquanly;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set<Donviquanly> getDonviquanlies() {
        return this.donviquanlies;
    }
    
    public void setDonviquanlies(Set<Donviquanly> donviquanlies) {
        this.donviquanlies = donviquanlies;
    }




}


