package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Phanquyen generated by hbm2java
 */
public class Phanquyen  implements java.io.Serializable {


     private Integer idphanquyen;
     private String ten;
     private Set soyeulylichs = new HashSet(0);

    public Phanquyen() {
    }

    public Phanquyen(String ten, Set soyeulylichs) {
       this.ten = ten;
       this.soyeulylichs = soyeulylichs;
    }
   
    public Integer getIdphanquyen() {
        return this.idphanquyen;
    }
    
    public void setIdphanquyen(Integer idphanquyen) {
        this.idphanquyen = idphanquyen;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getSoyeulylichs() {
        return this.soyeulylichs;
    }
    
    public void setSoyeulylichs(Set soyeulylichs) {
        this.soyeulylichs = soyeulylichs;
    }




}


