package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Phongban generated by hbm2java
 */
public class Phongban  implements java.io.Serializable {


     private Integer idphongban;
     private Donviquanly donviquanly;
     private String dienthoai;
     private String fax;
     private String thongtinchung;
     private String ten;
     private Set soyeulylichs = new HashSet(0);

    public Phongban() {
    }

	
    public Phongban(Donviquanly donviquanly) {
        this.donviquanly = donviquanly;
    }
    public Phongban(Donviquanly donviquanly, String dienthoai, String fax, String thongtinchung, String ten, Set soyeulylichs) {
       this.donviquanly = donviquanly;
       this.dienthoai = dienthoai;
       this.fax = fax;
       this.thongtinchung = thongtinchung;
       this.ten = ten;
       this.soyeulylichs = soyeulylichs;
    }
   
    public Integer getIdphongban() {
        return this.idphongban;
    }
    
    public void setIdphongban(Integer idphongban) {
        this.idphongban = idphongban;
    }
    public Donviquanly getDonviquanly() {
        return this.donviquanly;
    }
    
    public void setDonviquanly(Donviquanly donviquanly) {
        this.donviquanly = donviquanly;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getThongtinchung() {
        return this.thongtinchung;
    }
    
    public void setThongtinchung(String thongtinchung) {
        this.thongtinchung = thongtinchung;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getSoyeulylichs() {
        return this.soyeulylichs;
    }
    
    public void setSoyeulylichs(Set soyeulylichs) {
        this.soyeulylichs = soyeulylichs;
    }




}


