package model;
// Generated Jun 4, 2012 10:01:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Quocgia generated by hbm2java
 */
public class Quocgia  implements java.io.Serializable {


     private Integer idquocgia;
     private String ten;
     private Set quatrinhdinuocngoais = new HashSet(0);

    public Quocgia() {
    }

    public Quocgia(String ten, Set quatrinhdinuocngoais) {
       this.ten = ten;
       this.quatrinhdinuocngoais = quatrinhdinuocngoais;
    }
   
    public Integer getIdquocgia() {
        return this.idquocgia;
    }
    
    public void setIdquocgia(Integer idquocgia) {
        this.idquocgia = idquocgia;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set getQuatrinhdinuocngoais() {
        return this.quatrinhdinuocngoais;
    }
    
    public void setQuatrinhdinuocngoais(Set quatrinhdinuocngoais) {
        this.quatrinhdinuocngoais = quatrinhdinuocngoais;
    }




}


